#
# ---- Base Image ----
FROM node:12.21-alpine AS base

WORKDIR /opt/cron

RUN apk add --update --no-cache\
  bash \
  ca-certificates \
  cyrus-sasl-dev \
  g++ \
  lz4-dev \
  make \
  musl-dev \
  python \
  && \
  apk add --no-cache --virtual \
  .build-deps \
  gcc \
  zlib-dev \
  libc-dev \
  bsd-compat-headers \
  py-setuptools bash

CMD ["tail", "-f", "/dev/null"]

HEALTHCHECK --start-period=2m --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:9000/health || exit 1

